version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SqlServerP@ssword1
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: